"""added whitelist and black list

Revision ID: ea213e37fe64
Revises: 4c9312e0e5d9
Create Date: 2020-03-24 00:25:38.437583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea213e37fe64'
down_revision = '4c9312e0e5d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('black_url', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('black_url')
    )
    op.create_table('whitelist_url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('white_url', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('white_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whitelist_url')
    op.drop_table('blacklist_url')
    # ### end Alembic commands ###
